beep_poller: &beep_poller
  class: BeepPollerJob
  schedule: every 10 seconds

beeper_poller: &beeper_poller
  class: BeeperPollerJob
  schedule: every 10 seconds

runner_job_poller: &runner_job_poller
  class: RunnerJobPollerJob
  schedule: every 10 seconds

prune_beeper_runs: &prune_beeper_runs
  class: PruneBeeperRunsJob
  schedule: every day at 03:00

prune_channel_authorizations: &prune_channel_authorizations
  class: PruneChannelAuthorizationsJob
  schedule: every 10 minutes

prune_runner_authorizations: &prune_runner_authorizations
  class: PruneRunnerAuthorizationsJob
  schedule: every 10 minutes

development:
  beep_poller:
    <<: *beep_poller
  beeper_poller:
    <<: *beeper_poller
  runner_job_poller:
    <<: *runner_job_poller
  prune_beeper_runs:
    <<: *prune_beeper_runs
  prune_channel_authorizations:
    <<: *prune_channel_authorizations
  prune_runner_authorizations:
    <<: *prune_runner_authorizations

test:
  beep_poller:
    <<: *beep_poller
  beeper_poller:
    <<: *beeper_poller
  runner_job_poller:
    <<: *runner_job_poller
  prune_beeper_runs:
    <<: *prune_beeper_runs
  prune_channel_authorizations:
    <<: *prune_channel_authorizations
  prune_runner_authorizations:
    <<: *prune_runner_authorizations

production:
  beep_poller:
    <<: *beep_poller
  beeper_poller:
    <<: *beeper_poller
  runner_job_poller:
    <<: *runner_job_poller
  prune_beeper_runs:
    <<: *prune_beeper_runs
  prune_channel_authorizations:
    <<: *prune_channel_authorizations
  prune_runner_authorizations:
    <<: *prune_runner_authorizations
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every day at 00:00
