/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Account_slugRouteImport } from './routes/$account_slug'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DevRouteImport } from './routes/dev'
import { Route as MyRouteImport } from './routes/my'
import { Route as SignRouteImport } from './routes/sign'
import { Route as Account_slugIndexRouteImport } from './routes/$account_slug/index'
import { Route as Account_slugBeepersRouteImport } from './routes/$account_slug/beepers'
import { Route as Account_slugBeepsRouteImport } from './routes/$account_slug/beeps'
import { Route as Account_slugSettingsRouteImport } from './routes/$account_slug/settings'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as DevLettersRouteImport } from './routes/dev/letters'
import { Route as MyAccess_tokensRouteImport } from './routes/my/access_tokens'
import { Route as MySettingsRouteImport } from './routes/my/settings'
import { Route as SignIndexRouteImport } from './routes/sign/index'
import { Route as SignVerifyRouteImport } from './routes/sign/verify'
import { Route as Account_slugBeepersBeeperIdRouteImport } from './routes/$account_slug/beepers_.$beeperId'
import { Route as Account_slugBeepsBeepIdRouteImport } from './routes/$account_slug/beeps_.$beepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Account_slugRoute = Account_slugRouteImport.update({
  id: '/$account_slug',
  path: '/$account_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const Account_slugIndexRoute = Account_slugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Account_slugRoute,
} as any)
const Account_slugBeepersRoute = Account_slugBeepersRouteImport.update({
  id: '/beepers',
  path: '/beepers',
  getParentRoute: () => Account_slugRoute,
} as any)
const Account_slugBeepsRoute = Account_slugBeepsRouteImport.update({
  id: '/beeps',
  path: '/beeps',
  getParentRoute: () => Account_slugRoute,
} as any)
const Account_slugSettingsRoute = Account_slugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Account_slugRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const DevLettersRoute = DevLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => DevRoute,
} as any)
const MyAccess_tokensRoute = MyAccess_tokensRouteImport.update({
  id: '/access_tokens',
  path: '/access_tokens',
  getParentRoute: () => MyRoute,
} as any)
const MySettingsRoute = MySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MyRoute,
} as any)
const SignIndexRoute = SignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignRoute,
} as any)
const SignVerifyRoute = SignVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignRoute,
} as any)
const Account_slugBeepersBeeperIdRoute =
  Account_slugBeepersBeeperIdRouteImport.update({
    id: '/beepers_/$beeperId',
    path: '/beepers/$beeperId',
    getParentRoute: () => Account_slugRoute,
  } as any)
const Account_slugBeepsBeepIdRoute = Account_slugBeepsBeepIdRouteImport.update({
  id: '/beeps_/$beepId',
  path: '/beeps/$beepId',
  getParentRoute: () => Account_slugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$account_slug': typeof Account_slugRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/my': typeof MyRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/$account_slug/beepers': typeof Account_slugBeepersRoute
  '/$account_slug/beeps': typeof Account_slugBeepsRoute
  '/$account_slug/settings': typeof Account_slugSettingsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/dev/letters': typeof DevLettersRoute
  '/my/access_tokens': typeof MyAccess_tokensRoute
  '/my/settings': typeof MySettingsRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$account_slug/': typeof Account_slugIndexRoute
  '/sign/': typeof SignIndexRoute
  '/$account_slug/beepers/$beeperId': typeof Account_slugBeepersBeeperIdRoute
  '/$account_slug/beeps/$beepId': typeof Account_slugBeepsBeepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/my': typeof MyRouteWithChildren
  '/$account_slug/beepers': typeof Account_slugBeepersRoute
  '/$account_slug/beeps': typeof Account_slugBeepsRoute
  '/$account_slug/settings': typeof Account_slugSettingsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/dev/letters': typeof DevLettersRoute
  '/my/access_tokens': typeof MyAccess_tokensRoute
  '/my/settings': typeof MySettingsRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$account_slug': typeof Account_slugIndexRoute
  '/sign': typeof SignIndexRoute
  '/$account_slug/beepers/$beeperId': typeof Account_slugBeepersBeeperIdRoute
  '/$account_slug/beeps/$beepId': typeof Account_slugBeepsBeepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$account_slug': typeof Account_slugRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/my': typeof MyRouteWithChildren
  '/sign': typeof SignRouteWithChildren
  '/$account_slug/beepers': typeof Account_slugBeepersRoute
  '/$account_slug/beeps': typeof Account_slugBeepsRoute
  '/$account_slug/settings': typeof Account_slugSettingsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/dev/letters': typeof DevLettersRoute
  '/my/access_tokens': typeof MyAccess_tokensRoute
  '/my/settings': typeof MySettingsRoute
  '/sign/verify': typeof SignVerifyRoute
  '/$account_slug/': typeof Account_slugIndexRoute
  '/sign/': typeof SignIndexRoute
  '/$account_slug/beepers_/$beeperId': typeof Account_slugBeepersBeeperIdRoute
  '/$account_slug/beeps_/$beepId': typeof Account_slugBeepsBeepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$account_slug'
    | '/accounts'
    | '/admin'
    | '/dev'
    | '/my'
    | '/sign'
    | '/$account_slug/beepers'
    | '/$account_slug/beeps'
    | '/$account_slug/settings'
    | '/admin/jobs'
    | '/admin/stats'
    | '/dev/letters'
    | '/my/access_tokens'
    | '/my/settings'
    | '/sign/verify'
    | '/$account_slug/'
    | '/sign/'
    | '/$account_slug/beepers/$beeperId'
    | '/$account_slug/beeps/$beepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/admin'
    | '/dev'
    | '/my'
    | '/$account_slug/beepers'
    | '/$account_slug/beeps'
    | '/$account_slug/settings'
    | '/admin/jobs'
    | '/admin/stats'
    | '/dev/letters'
    | '/my/access_tokens'
    | '/my/settings'
    | '/sign/verify'
    | '/$account_slug'
    | '/sign'
    | '/$account_slug/beepers/$beeperId'
    | '/$account_slug/beeps/$beepId'
  id:
    | '__root__'
    | '/'
    | '/$account_slug'
    | '/accounts'
    | '/admin'
    | '/dev'
    | '/my'
    | '/sign'
    | '/$account_slug/beepers'
    | '/$account_slug/beeps'
    | '/$account_slug/settings'
    | '/admin/jobs'
    | '/admin/stats'
    | '/dev/letters'
    | '/my/access_tokens'
    | '/my/settings'
    | '/sign/verify'
    | '/$account_slug/'
    | '/sign/'
    | '/$account_slug/beepers_/$beeperId'
    | '/$account_slug/beeps_/$beepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Account_slugRoute: typeof Account_slugRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  MyRoute: typeof MyRouteWithChildren
  SignRoute: typeof SignRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$account_slug': {
      id: '/$account_slug'
      path: '/$account_slug'
      fullPath: '/$account_slug'
      preLoaderRoute: typeof Account_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$account_slug/': {
      id: '/$account_slug/'
      path: '/'
      fullPath: '/$account_slug/'
      preLoaderRoute: typeof Account_slugIndexRouteImport
      parentRoute: typeof Account_slugRoute
    }
    '/$account_slug/beepers': {
      id: '/$account_slug/beepers'
      path: '/beepers'
      fullPath: '/$account_slug/beepers'
      preLoaderRoute: typeof Account_slugBeepersRouteImport
      parentRoute: typeof Account_slugRoute
    }
    '/$account_slug/beeps': {
      id: '/$account_slug/beeps'
      path: '/beeps'
      fullPath: '/$account_slug/beeps'
      preLoaderRoute: typeof Account_slugBeepsRouteImport
      parentRoute: typeof Account_slugRoute
    }
    '/$account_slug/settings': {
      id: '/$account_slug/settings'
      path: '/settings'
      fullPath: '/$account_slug/settings'
      preLoaderRoute: typeof Account_slugSettingsRouteImport
      parentRoute: typeof Account_slugRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dev/letters': {
      id: '/dev/letters'
      path: '/letters'
      fullPath: '/dev/letters'
      preLoaderRoute: typeof DevLettersRouteImport
      parentRoute: typeof DevRoute
    }
    '/my/access_tokens': {
      id: '/my/access_tokens'
      path: '/access_tokens'
      fullPath: '/my/access_tokens'
      preLoaderRoute: typeof MyAccess_tokensRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/settings': {
      id: '/my/settings'
      path: '/settings'
      fullPath: '/my/settings'
      preLoaderRoute: typeof MySettingsRouteImport
      parentRoute: typeof MyRoute
    }
    '/sign/': {
      id: '/sign/'
      path: '/'
      fullPath: '/sign/'
      preLoaderRoute: typeof SignIndexRouteImport
      parentRoute: typeof SignRoute
    }
    '/sign/verify': {
      id: '/sign/verify'
      path: '/verify'
      fullPath: '/sign/verify'
      preLoaderRoute: typeof SignVerifyRouteImport
      parentRoute: typeof SignRoute
    }
    '/$account_slug/beepers_/$beeperId': {
      id: '/$account_slug/beepers_/$beeperId'
      path: '/beepers/$beeperId'
      fullPath: '/$account_slug/beepers/$beeperId'
      preLoaderRoute: typeof Account_slugBeepersBeeperIdRouteImport
      parentRoute: typeof Account_slugRoute
    }
    '/$account_slug/beeps_/$beepId': {
      id: '/$account_slug/beeps_/$beepId'
      path: '/beeps/$beepId'
      fullPath: '/$account_slug/beeps/$beepId'
      preLoaderRoute: typeof Account_slugBeepsBeepIdRouteImport
      parentRoute: typeof Account_slugRoute
    }
  }
}

interface Account_slugRouteChildren {
  Account_slugBeepersRoute: typeof Account_slugBeepersRoute
  Account_slugBeepsRoute: typeof Account_slugBeepsRoute
  Account_slugSettingsRoute: typeof Account_slugSettingsRoute
  Account_slugIndexRoute: typeof Account_slugIndexRoute
  Account_slugBeepersBeeperIdRoute: typeof Account_slugBeepersBeeperIdRoute
  Account_slugBeepsBeepIdRoute: typeof Account_slugBeepsBeepIdRoute
}

const Account_slugRouteChildren: Account_slugRouteChildren = {
  Account_slugBeepersRoute: Account_slugBeepersRoute,
  Account_slugBeepsRoute: Account_slugBeepsRoute,
  Account_slugSettingsRoute: Account_slugSettingsRoute,
  Account_slugIndexRoute: Account_slugIndexRoute,
  Account_slugBeepersBeeperIdRoute: Account_slugBeepersBeeperIdRoute,
  Account_slugBeepsBeepIdRoute: Account_slugBeepsBeepIdRoute,
}

const Account_slugRouteWithChildren = Account_slugRoute._addFileChildren(
  Account_slugRouteChildren,
)

interface AdminRouteChildren {
  AdminJobsRoute: typeof AdminJobsRoute
  AdminStatsRoute: typeof AdminStatsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJobsRoute: AdminJobsRoute,
  AdminStatsRoute: AdminStatsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DevRouteChildren {
  DevLettersRoute: typeof DevLettersRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevLettersRoute: DevLettersRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface MyRouteChildren {
  MyAccess_tokensRoute: typeof MyAccess_tokensRoute
  MySettingsRoute: typeof MySettingsRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyAccess_tokensRoute: MyAccess_tokensRoute,
  MySettingsRoute: MySettingsRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

interface SignRouteChildren {
  SignVerifyRoute: typeof SignVerifyRoute
  SignIndexRoute: typeof SignIndexRoute
}

const SignRouteChildren: SignRouteChildren = {
  SignVerifyRoute: SignVerifyRoute,
  SignIndexRoute: SignIndexRoute,
}

const SignRouteWithChildren = SignRoute._addFileChildren(SignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Account_slugRoute: Account_slugRouteWithChildren,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  MyRoute: MyRouteWithChildren,
  SignRoute: SignRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
