json.valid @preview.valid?
json.errors @preview.errors
json.kind @preview.kind
json.title @preview.title
json.body @preview.body
json.intent @preview.intent
json.metadata @preview.metadata
json.timezone @preview.timezone
json.notification_channels @preview.notification_channels
json.run_at @preview.run_at&.iso8601
json.next_run_at @preview.next_run_at&.iso8601
json.cron @preview.cron
json.schedule_key @preview.schedule_key
json.schedule_display @preview.schedule_display
